on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # schedule:
  #   - cron: '0 */11 * * *'

permissions:
  contents: read

# Setting up the reusable deploy workflow as individual jobs 
# allows each deployment to execute in parallel with minimal 
# dependency on each other.
jobs:

  # =================================================
  # nodejs-docs-samples
  # =================================================
  nodejs18:
    permissions:
      contents: write
      actions: read
      id-token: write
    uses: ./.github/workflows/fn-deploy.yaml
    with:
      repo: "https://github.com/GoogleCloudPlatform/nodejs-docs-samples.git"
      context: "nodejs-docs-samples/functions/helloworld/helloworldGet/"
      name: "daily-nodejs18"
      runtime: "nodejs18"
      entry_point: "helloGET"

  nodejs16:
    permissions:
      contents: write
      actions: read
      id-token: write
    uses: ./.github/workflows/fn-deploy.yaml
    with:
      repo: "https://github.com/GoogleCloudPlatform/nodejs-docs-samples.git"
      context: "nodejs-docs-samples/functions/helloworld/helloworldGet/"
      name: "daily-nodejs16"
      runtime: "nodejs16"
      entry_point: "helloGET"

  nodejs14:
    permissions:
      contents: write
      actions: read
      id-token: write
    uses: ./.github/workflows/fn-deploy.yaml
    with:
      repo: "https://github.com/GoogleCloudPlatform/nodejs-docs-samples.git"
      context: "nodejs-docs-samples/functions/helloworld/helloworldGet/"
      name: "daily-nodejs14"
      runtime: "nodejs14"
      entry_point: "helloGET"

  # =================================================
  # python-docs-samples
  # =================================================
  python311:
    permissions:
      contents: write
      actions: read
      id-token: write
    uses: ./.github/workflows/fn-deploy.yaml
    with:
      repo: "https://github.com/GoogleCloudPlatform/python-docs-samples.git"
      context: "python-docs-samples/functions/helloworld/"
      name: "daily-python311"
      runtime: "python311"
      entry_point: "hello_get"

  python310:
    permissions:
      contents: write
      actions: read
      id-token: write
    uses: ./.github/workflows/fn-deploy.yaml
    with:
      repo: "https://github.com/GoogleCloudPlatform/python-docs-samples.git"
      context: "python-docs-samples/functions/helloworld/"
      name: "daily-python310"
      runtime: "python310"
      entry_point: "hello_get"

  python39:
    permissions:
      contents: write
      actions: read
      id-token: write
    uses: ./.github/workflows/fn-deploy.yaml
    with:
      repo: "https://github.com/GoogleCloudPlatform/python-docs-samples.git"
      context: "python-docs-samples/functions/helloworld/"
      name: "daily-python39"
      runtime: "python39"
      entry_point: "hello_get"

  # =================================================
  # golang-samples
  # =================================================
  go120:
    permissions:
      contents: write
      actions: read
      id-token: write
    uses: ./.github/workflows/fn-deploy.yaml
    with:
      repo: "https://github.com/GoogleCloudPlatform/golang-samples.git"
      context: "golang-samples/functions/functionsv2/helloworld/"
      name: "daily-go120"
      runtime: "go120"
      entry_point: "HelloGet"

  go119:
    permissions:
      contents: write
      actions: read
      id-token: write
    uses: ./.github/workflows/fn-deploy.yaml
    with:
      repo: "https://github.com/GoogleCloudPlatform/golang-samples.git"
      context: "golang-samples/functions/functionsv2/helloworld/"
      name: "daily-go119"
      runtime: "go119"
      entry_point: "HelloGet"

  go118:
    permissions:
      contents: write
      actions: read
      id-token: write
    uses: ./.github/workflows/fn-deploy.yaml
    with:
      repo: "https://github.com/GoogleCloudPlatform/golang-samples.git"
      context: "golang-samples/functions/functionsv2/helloworld/"
      name: "daily-go118"
      runtime: "go118"
      entry_point: "HelloGet"

  # =================================================
  # java-docs-samples
  # =================================================
  java17:
    permissions:
      contents: write
      actions: read
      id-token: write
    uses: ./.github/workflows/fn-deploy.yaml
    with:
      repo: "https://github.com/GoogleCloudPlatform/java-docs-samples.git"
      context: "java-docs-samples/functions/helloworld/helloworld/"
      name: "daily-java17"
      runtime: "java17"
      entry_point: "functions.HelloWorld"
      memory: "512MB"

  java11:
    permissions:
      contents: write
      actions: read
      id-token: write
    uses: ./.github/workflows/fn-deploy.yaml
    with:
      repo: "https://github.com/GoogleCloudPlatform/java-docs-samples.git"
      context: "java-docs-samples/functions/helloworld/helloworld/"
      name: "daily-java11"
      runtime: "java11"
      entry_point: "functions.HelloWorld"
      memory: "512MB"

  # =================================================
  # dotnet-docs-samples
  # =================================================
  dotnet6:
    permissions:
      contents: write
      actions: read
      id-token: write
    uses: ./.github/workflows/fn-deploy.yaml
    with:
      repo: "https://github.com/GoogleCloudPlatform/dotnet-docs-samples.git"
      context: "dotnet-docs-samples/functions/helloworld/HelloWorld/"
      name: "daily-dotnet6"
      runtime: "dotnet6"
      entry_point: "HelloWorld.Function"
  
  # The sample in repo doesn't deploy for dotnet3 so using local sample.
  # Notice repo is not specified, context is different, and checkout == true.
  dotnet3:
    permissions:
      contents: write
      actions: read
      id-token: write
    uses: ./.github/workflows/fn-deploy.yaml
    with:
      context: "src/dotnet3"
      checkout: true
      name: "daily-dotnet3"
      runtime: "dotnet3"
      entry_point: "HelloHttp.Function"

  # =================================================
  # ruby-docs-samples
  # =================================================
  ruby30:
    permissions:
      contents: write
      actions: read
      id-token: write
    uses: ./.github/workflows/fn-deploy.yaml
    with:
      repo: "https://github.com/GoogleCloudPlatform/ruby-docs-samples.git"
      context: "ruby-docs-samples/functions/helloworld/get/"
      name: "daily-ruby30"
      runtime: "ruby30"
      entry_point: "hello_get"

  ruby27:
    permissions:
      contents: write
      actions: read
      id-token: write
    uses: ./.github/workflows/fn-deploy.yaml
    with:
      repo: "https://github.com/GoogleCloudPlatform/ruby-docs-samples.git"
      context: "ruby-docs-samples/functions/helloworld/get/"
      name: "daily-ruby27"
      runtime: "ruby27"
      entry_point: "hello_get"

  ruby26:
    permissions:
      contents: write
      actions: read
      id-token: write
    uses: ./.github/workflows/fn-deploy.yaml
    with:
      repo: "https://github.com/GoogleCloudPlatform/ruby-docs-samples.git"
      context: "ruby-docs-samples/functions/helloworld/get/"
      name: "daily-ruby26"
      runtime: "ruby26"
      entry_point: "hello_get"

  # =================================================
  # php-docs-samples
  # =================================================
  php81:
    permissions:
      contents: write
      actions: read
      id-token: write
    uses: ./.github/workflows/fn-deploy.yaml
    with:
      repo: "https://github.com/GoogleCloudPlatform/php-docs-samples.git"
      context: "php-docs-samples/functions/helloworld_get/"
      name: "daily-php81"
      runtime: "php81"
      entry_point: "helloGet"

  php74:
    permissions:
      contents: write
      actions: read
      id-token: write
    uses: ./.github/workflows/fn-deploy.yaml
    with:
      repo: "https://github.com/GoogleCloudPlatform/php-docs-samples.git"
      context: "php-docs-samples/functions/helloworld_get/"
      name: "daily-php74"
      runtime: "php74"
      entry_point: "helloGet"